genInitConf:
	g++ genInitConf.cpp -std=c++11 -O3 -lproteinManager -o genInitConf
	mv ./genInitConf ./data
addCargo:
	g++ addCargo.cpp -std=c++11 -O3 -lproteinManager -o addCargo
	mv ./addCargo ./data
