genInitConf:
	g++ genInitConf.cpp -std=c++11 -O3 -lproteinManager
genInitConf_cg:
	g++ genInitConf_cg.cpp -std=c++11 -O3 -lproteinManager
genInitConf_tip:
	g++ genInitConf_tip.cpp -std=c++11 -O3 -lproteinManager
